# Generated by Django 6.0.1 on 2026-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='episode_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
